packaging_format = 2

id = "umami"
name = "Umami"
description.en = "Simple, fast, privacy-focused alternative to Google Analytics"
description.fr = "Analyse de trafic web simple et respectueux"

version = "1.40.0~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "MIT"
website = "https://umami.is/"
demo = "https://app.umami.is/share/8rmHaheU/umami.is"
admindoc = "https://umami.is/docs/about"
code = "https://github.com/mikecao/umami"

[integration]
yunohost = ">= 11.1.6"
architectures = "all"
multi_instance = true
ldap = "?"
sso = "?"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
        [[resources.apt.extras]]
        repo = "deb https://dl.yarnpkg.com/debian/ stable main"
        key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
        packages = "yarn"

    [resources.database]
    type = "postgresql"
