#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir"]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.language = "fr-FR"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.6dd4c32baa041b2099bdcb7e11c880433c2b35a9.name = "Upgrade from 2.19.0~ynh1"