test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = "install.subdir"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.eb20586e7add0ee1f6da31bbe6fd8d7fe245c036.name = "Upgrade from 1.40"
