test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = "install.subdir"

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.4860e2cc.name = "Upgrade from 1.33~ynh2"
