#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

# Install Nodejs
ynh_nodejs_install

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/build"
chown -R $app:$app $install_dir/build

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Web Analytics" --log="/var/log/$app/$app.log"

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

ynh_config_add --template=".env" --destination="$install_dir/build/.env"

chmod 650 "$install_dir/build/.env"

ynh_script_progression "Provisioning pgcrypto..."

ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

#=================================================
# CONFIGURE THE APP
#=================================================
ynh_script_progression "Configuring the app..."

pushd "$install_dir/build"
	ynh_hide_warnings ynh_exec_as_app yarn install
	ynh_hide_warnings ynh_exec_as_app NEXT_TELEMETRY_DISABLED=1 yarn build

	# Actual app is a subset of release assets
	# List of deps based on Dockerfile: https://github.com/umami-software/umami/blob/master/Dockerfile
	ynh_safe_rm "node_modules/"
	mv next.config.js .next/standalone/
	mv public .next/standalone/
	mv prisma .next/standalone/
	mv scripts .next/standalone/
	mv .next/static .next/standalone/.next
popd

mkdir "$install_dir/release"
chmod -R o-rwx "$install_dir/release"
chown -R $app:www-data "$install_dir/release"

mv -f $install_dir/build/.next/standalone/* $install_dir/build/.next/standalone/.[!.]* $install_dir/release

pushd "$install_dir/release"
	ynh_hide_warnings ynh_exec_as_app yarn add npm-run-all dotenv prisma
popd

ynh_safe_rm "$install_dir/.cache"

ynh_safe_rm "$install_dir/build"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
