#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Provisioning pgcrypto..."

ynh_psql_db_shell <<< "CREATE EXTENSION IF NOT EXISTS pgcrypto;"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

# Create a dedicated systemd config
ynh_config_add_systemd
yunohost service add "$app" --description="Web Analytics" --log="/var/log/$app/$app.log"

#=================================================
# CONFIGURE THE APP
#=================================================
ynh_script_progression "Configuring and building the app..."

app_secret=$(openssl rand -hex 32)
two_factor_encryption_key=$(openssl rand -hex 32)
ynh_app_setting_set --key=app_secret --value=$app_secret
ynh_app_setting_set --key=two_factor_encryption_key --value=$two_factor_encryption_key

myynh_build

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service="$app" --action="start" --wait_until="Ready in" --log_path="systemd"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
